### ISSUE TITLE
ios 9.2 Errors

### ISSUE THREAD

**Issue by hardik42** [Azure/azure-storage-ios#13]
The code doesnt seem to build on xcode 7.2

**Comment by mirobers** [comment]
Can you share the errors you get while building?

**Comment by hardik42** [comment]
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: can't open input file: /Users/Hardik/Library/Developer/Xcode/DerivedData/Azure_Storage_Client_Library-hbaiwjzytbwpbqdzevhzrmefscma/Build/Products/Debug-iphoneos/libAzure Storage Client Library.a (No such file or directory)

**Comment by Nicolas-Isaza** [comment]
Encountered same problem. Any solution?

**Comment by Berdikhan** [comment]
Facing same issue

**Comment by Nicolas-Isaza** [comment]
I removed the library and added it via cocoapods. Works fine now.

**Comment by asorrin-msft** [comment]
Weird, a couple of us are using the XCode 7.2 and everything seems to work fine.  Using the CocoaPod is certainly an option, if you don't want to modify the library.  Usually for me, problems like this go away when I explicitly tell XCode to build clean.   Otherwise, I'm not sure what the problem might be.

**Comment by vtcajones** [comment]
Yeah, I'm having the same issue. Xcode 7.2 building clean didn't fix it.

**Comment by Berdikhan** [comment]
I have added using pods and it works fine for me. Thanks

**Comment by micurd** [comment]
Hmmm I can't repro this issue and I have Xcode 7.2. What I've done so far:
1. Cloned this repo
2. Built the "Azure Storage Client Library" target. No errors
3. Built the "Framework" target (which generates the "Azure Storage Client Library.framework" file to desktop). No errors
4. Created a new project 
5. Added framework file and libxml2.2 to "Link Binary with Libraries"
<img width="981" alt="screen shot 2016-01-07 at 2 39 24 pm" src="https://cloud.githubusercontent.com/assets/8452922/12184908/f41f966c-b54c-11e5-9d4a-caccd43792a2.png">
6. Added the path to my Desktop to Framework Search Paths
<img width="580" alt="screen shot 2016-01-07 at 2 43 40 pm" src="https://cloud.githubusercontent.com/assets/8452922/12184953/25582a32-b54d-11e5-9bc0-6d08ede14709.png">
7. Added the import statement, some sample code, and everything worked fine
<img width="614" alt="screen shot 2016-01-07 at 2 45 33 pm" src="https://cloud.githubusercontent.com/assets/8452922/12184992/64bfd3aa-b54d-11e5-83cb-510c20dc07b9.png">

I've done a little research and this issue looks similar to the following Stack Overflow post:
http://stackoverflow.com/questions/24967290/xcode-compile-error-lipo-cant-open-input-file

For those who have this issue, how do your architecture settings look? My architecture settings look like the following:
<img width="739" alt="screen shot 2016-01-07 at 2 49 22 pm" src="https://cloud.githubusercontent.com/assets/8452922/12185096/f07d5f7a-b54d-11e5-83e9-9e3bef45d362.png">

**Comment by phantomlight** [comment]
I'm having this same issue. It's a bit frustrating. /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: can't open input file: /Users/Hardik/Library/Developer/Xcode/DerivedData/Azure_Storage_Client_Library-hbaiwjzytbwpbqdzevhzrmefscma/Build/Products/Debug-iphoneos/libAzure Storage Client Library.a (No such file or directory)

cocoapods only have api for swfit - I'm using Objective C... any Ideas?

**Comment by asorrin-msft** [comment]
Hey all - 
Sorry we haven't fixed this yet, something else came up that I thought was more urgent.  (There's a race condition that sometimes causes calls to never complete.  We have a fix, should be shipped in a couple days.)

I believe I know what the issue is - a problem with the framework-building script.  We'll be testing a fix over the next couple days.  To workaround for now, please use the CocoaPod :)  Also, you can try selecting the Azure Storage Client Library target, building for the iOS Simulator AND the iOS device (have to build it twice), and then building the Framework - that should work as well.

@phantomlight - The official Cocoapod (https://cocoapods.org/pods/AZSClient) should work for both Objective-C and Swift, is there some particular error you're getting?

**Comment by micurd** [comment]
@phantomlight @hardik42 @Nicolas-Isaza @Berdikhan @vtcajones did you all encounter this problem when building the "Azure Storage Client Library" target? 
<img width="295" alt="screen shot 2016-01-20 at 9 12 33 am" src="https://cloud.githubusercontent.com/assets/8452922/12456729/f94ef426-bf55-11e5-8276-69dddb3cb22e.png">

or the "Framework" target?
<img width="217" alt="screen shot 2016-01-20 at 9 11 10 am" src="https://cloud.githubusercontent.com/assets/8452922/12456698/db5b07ac-bf55-11e5-893b-91879079de95.png">

**Comment by NT-D** [comment]
@micurd I'm new in this thread. I can only repro same problem when building the "Framework" target.
![image](https://cloud.githubusercontent.com/assets/8452922/12456698/db5b07ac-bf55-11e5-893b-91879079de95.png)

**Comment by aw230012** [comment]
I've tried both the framework build methods shown here and the Cocoapod and none of them are building.  I receive the same framework build error as above, and for the Cocoapod I receive 3 build errors.  See attached snapshot.
![screen shot 2016-02-03 at 4 58 29 pm](https://cloud.githubusercontent.com/assets/8516152/12798346/e5ac5fe8-ca96-11e5-93af-461b0dc3181e.png)

**Comment by vinbhai4u** [comment]
@aw230012 I am also facing the same, did you fix yours??

**Comment by abhishekNebQuovantis** [comment]
I installed the AZSClient into my project(swift) through cocoa pods and it's working fine with Xcode 7.3.1. 
But when i install the  Xcode-8(Xcode 7.3.1  also exists) on my machine. 

Now I run my project with Xcode 7.3.1 and now it shows me the same above error which is faced by @aw230012. 
![](https://cloud.githubusercontent.com/assets/8516152/12798346/e5ac5fe8-ca96-11e5-93af-461b0dc3181e.png)

Now again i deleted Xcode 8, cleaned up and cleaned derived data. Now again it's working fine in Xcode 7.3.1

Can anyone help me same??

**Comment by zezha-msft** [comment]
Closing this now since it should have been fixed already.

Concerning the ASL error, this problem should now be solved with the latest version 0.2.3. Please let us know if you still encounter any problem.

I apologize for the lack of updates these last few months. I assure you that we are committed to make this library better and will update it significantly more frequently from now on.

**Comment by abrez** [comment]
I have installed version 0.2.5 but still, i am getting this error please help.
but if I remove armv7 its works great but in the version below iPhone 6 the is not installing please help
![screen shot 2018-02-09 at 5 12 36 pm](https://user-images.githubusercontent.com/12423023/36027259-83e18030-0dc0-11e8-9009-78cf461b0d24.png)
