### ISSUE TITLE
Swift implementation

### ISSUE THREAD

**Issue by aliyasar** [Azure/azure-storage-ios#15]
Will there be Swift implementation to the Blob Storage?

**Comment by saadatbhatti** [comment]
When this will be released? Can this pre-release version can be used for Prod?

**Comment by asorrin-msft** [comment]
Swift implementation - We will probably not be writing the library itself in Swift, but as of v0.1.1 it should be fully compatible.  The sample project (a simple iOS app) is written in Swift.  Are there specific reasons you'd like to see the library written in Swift as well?  We'd like for people to be able to access the library using both Objective-C and Swift.

Release - We usually don't release a library as 'GA' until we've gotten feedback from a number of customers who have been using a pre-release version.  That way, we are more confident that there aren't many bugs, performance issues, etc.  We've done testing on our side, but it's always good to have some customer feedback before we GA.
If you want to use the library in its current state, that would be great, but we recommend that you do extensive testing for your application's scenarios.  Please do give us any feedback you may have!
Also, we are more likely to make breaking changes from one version to the next while the library is still pre-GA.  Otherwise, support for the iOS storage client will be the same as the other-language storage clients we have, in terms of bug fixes, etc.

**Comment by saadatbhatti** [comment]
So this can be used for Production ?

**Comment by asorrin-msft** [comment]
That's up to you, it depends on your risk tolerance and test coverage.  It has not been used in many production scenarios yet, and is still prerelease.

**Comment by micurd** [comment]
Hi @saadatbhatti if you have additional questions relating to production, please open a separate issue and we’d be happy to discuss this.

**Comment by aliyasar** [comment]
Thank you for your extensive answer. @asorrin-msft
