### ISSUE TITLE
Include of non modular header

### ISSUE THREAD

**Issue by vineethvijayan** [Azure/azure-storage-ios#20]
I am trying to use the library via cocoa pods,

`pod  'AZSClient'`

ran pod install and everything went well

but when I try to use it in the project 

`import AZSClient`

Project doesn't build

![screen shot 2016-02-11 at 5 12 31 pm](https://cloud.githubusercontent.com/assets/6049347/12975560/b7bdc200-d0e2-11e5-875b-d932fc7e1524.png)

I am using in a swift project 

Any help much appreciated

**Comment by Ruthberg** [comment]
I have exactly the same problem, any progress on this?

**Comment by Ruthberg** [comment]
I cleared Header Search Path in the Pods project build settings. That got rid og this error, but now I have another one. 'libxml/xmlwriter.h' file not found. Thought I'd post this in case it would help you along...

**Comment by damienpontifex** [comment]
I found that this was due to the `#include <asl.h>` at the top of AZSOperationContext.h but still looking for a solution to the problem.

**Comment by Ruthberg** [comment]
Ok, well I have succeeded in using this framework, but dropped the pod. Just downloaded the sourcecode and compiled it, included it to the project and made a bridging-header. Works like a charm, but then updating it later may become a more manual job. I simply did not have time to make this pod system work.

**Comment by zezha-msft** [comment]
@vineethvijayan @Ruthberg @damienpontifex 

Really sorry for the late reply!

If you are still encountering this issue, I think that it might be because you are using the "use_frameworks!" option with Xcode 7. I've tested the latest version 0.2.3 with "use_frameworks!" in Xcode 8, and it works fine. To avoid this problem, you could either switch to Xcode 8, or drop the "use_frameworks!" option and create a bridging header instead (please refer to Readme for instructions).

Please reopen this issue if you're still seeing this problem.
