### ISSUE TITLE
Feedback Request: 3-min survey for Azure Storage Client Libraries and Tools 

### ISSUE THREAD

**Issue by seguler** [Azure/azure-storage-ios#43]
Hi Everyone,

This is your chance to shape the Azure Storage product roadmap! We are looking for feedback from our users regarding Azure Storage Client Library and Tools. If you'd like to help us, please take the following short survey: http://aka.ms/ClientLibrariesFeedback2016

Sercan Guler
Program Manager, Azure Storage

**Comment by epot** [comment]
Done. Would it be possible to get visibility on the roadmap of this specific component. It is still in a pre-release state and it seems no one is working on it for the last 7 months. Is there any concrete (with strong commitments) to do an official release and get closer to the level of features offered by the competition ?

**Comment by micurd** [comment]
Hi @epot. Our team would love to get your feedback directly. Can you email us at storageios at microsoft dot com? We'd like to better understand the level of features you're expecting from this library. Thanks!

**Comment by epot** [comment]
Isn't it a pity not to have those discussions publicly since this is an open source project ? 
I was using AWS before as a cloud provider and the S3 transfer utility coming along the iOS and Android SDK is extremely nice. It provides (and probably many other things):

- ability to start/stop/pause transfers
- ability to continue transferring data in the background
- ability to persist transfers on the phone in case the app is stopped and restarted
- ability to start easily several transfers in parallel and track their progress
- ...

I was using all those very nice features and when I find that none of them exists and there was no commit during the past 7 months on what is already a very poor (in terms of feature) equivalent on Azure, I am a bit worried.

**Comment by epot** [comment]
I am not sure if I am the only one, but I am having a lot of crashes with the current library. Since many issues are opened for months/years with no answer from Microsoft, and since it does not seem to get a better visibility of where this component is going, I am personally giving up. I will see what is possible by targetting the REST API directly.

**Comment by micurd** [comment]
Hi @epot we apologize for any frustrations you've experienced when using this library. I agree that not having any commits for such a long period of time is a very bad look. We're still very committed to improving this library and plan to make more updates in early 2017. In the meantime, I'll be tracking your suggestions in our backlog. Thank you for your feedback.

**Comment by zezha-msft** [comment]
Closing with @seguler's permission.
