### ISSUE TITLE
Archive the project show error!!!

### ISSUE THREAD

**Issue by mhty19891833** [Azure/azure-storage-ios#87]
ld: warning: ignoring file /Users/ty19891833/Desktop/Servant/AZSClient.framework/AZSClient, missing required architecture armv7 in file /Users/xxx/Desktop/Servant/AZSClient.framework/AZSClient (2 slices)
Undefined symbols for architecture armv7:
  "_OBJC_CLASS_$_AZSCloudStorageAccount", referenced from:
      objc-class-ref in ServerConfiguration.o
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

need your answer!

**Comment by zezha-msft** [comment]
Hi @mhty19891833, thanks for reporting this issue. I reproduced in my local environment and logged it for investigation.

**Comment by zezha-msft** [comment]
Hi @mhty19891833, I realized that we dropped support for armv7 and armv7s, since they are not supported by the latest iOS. The change was made [here](https://github.com/Azure/azure-storage-ios/commit/2f48d7276ac6ad370bee8269b1fa1a68ed3647e2). If you would like to generate a library that supports the older architectures, reverting this [line](https://github.com/Azure/azure-storage-ios/commit/2f48d7276ac6ad370bee8269b1fa1a68ed3647e2#diff-99e82f95808072ccc10f51f4957b2d9aL739) should work. Sorry for the inconvenience!

**Comment by ElizaSapir** [comment]
@zezha-msft I have same issue with my SDK, 

What is missing?

```
xcodebuild clean build \
           -project ${product_name}.xcodeproj \
						-scheme ${product_name} \
						-sdk iphoneos \
						-configuration Release \
						CODE_SIGNING_REQUIRED=NO \
						BITCODE_GENERATION_MODE=bitcode \
						OTHER_CFLAGS="-fembed-bitcode" \
						-derivedDataPath "${build_dir}" #| xcpretty

xcodebuild clean build \
           -project ${product_name}.xcodeproj \
						-scheme ${product_name} \
						-sdk iphonesimulator \
						VALID_ARCHS="x86_64 i386" \
						-destination 'platform=iOS Simulator,name=iPhone 8' \
						BITCODE_GENERATION_MODE=bitcode \
						OTHER_CFLAGS="-fembed-bitcode" \
						-configuration Release \
						-derivedDataPath "${build_dir}" #| xcpretty
```
